// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NobelConsole.Data;

namespace NobelConsole.Migrations
{
    [DbContext(typeof(AdatContext))]
    [Migration("20220205123636_elso")]
    partial class elso
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NobelConsole.Models.Adat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ev")
                        .HasColumnType("int");

                    b.Property<string>("KeresztNev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipusId")
                        .HasColumnType("int");

                    b.Property<string>("VezetekNev")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipusId");

                    b.ToTable("Nobel");
                });

            modelBuilder.Entity("NobelConsole.Models.Fajta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipusok");
                });

            modelBuilder.Entity("NobelConsole.Models.Adat", b =>
                {
                    b.HasOne("NobelConsole.Models.Fajta", "Tipus")
                        .WithMany()
                        .HasForeignKey("TipusId");

                    b.Navigation("Tipus");
                });
#pragma warning restore 612, 618
        }
    }
}
